version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_cursos
    restart: always
    ports:
      - "5434:5432"  # Host:Container
    environment:
      POSTGRES_DB: courses_db
      POSTGRES_USER: giovana
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
